---
title: "Python Notebook"
output: rmarkdown::github_document
---


```{}
Dont forget to use 'source .venv/Scripts/activate' command first
then 'pip install -r requirements.txt' to install are required packages
```


```{r}
Sys.getenv("RETICULATE_PYTHON")
library(reticulate)
use_python(".venv/bin/python")
```


```{python packages}

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

```



```{python }

def dist_lognormal():
  np.random.seed(0)
  return np.random.lognormal(size=1000)

plt.hist(dist_lognormal())
plt.show()
```

```{r}

readr::write_csv(nycflights13::flights,path = "flights.csv")

```



```{python import data}

heights = pd.read_csv("data/heights.csv")
heights.head

```

```{r}

head(py$heights)

```


```{r but plot in R}
library(ggplot2)
py$heights
ggplot(py$heights, aes(age, earn)) +
  geom_violin(aes(color=sex))
```


```{ }
Run in terminal the following to transform a Rmd extension to ipynb by using jupytext
--> jupytext --to notebook some_notebook.Rmd
```

